from pathlib import Path
p=Path('/tmp/api.php'); s=p.read_text(); marker="if ($action === 'google_login' && $_SERVER['REQUEST_METHOD'] === 'POST') {"
block=r'''
if ($action === 'profile_stats' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->prepare('SELECT (SELECT COUNT(*) FROM posts WHERE author_id=:id) posts,(SELECT COUNT(*) FROM follows WHERE following_id=:id) followers,(SELECT COUNT(*) FROM follows WHERE follower_id=:id) following');$q->execute([':id'=>$u['id']]);$r=$q->fetch();respond(['ok'=>true,'data'=>['posts'=>(int)$r['posts'],'followers'=>(int)$r['followers'],'following'=>(int)$r['following']]]); }
if ($action === 'follow_toggle' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$target=trim((string)($d['user_id']??''));if($target===''||$target===$u['id'])respond(['ok'=>false,'error'=>'invalid_target'],422);$q=$pdo->prepare('SELECT 1 FROM follows WHERE follower_id=:f AND following_id=:t');$q->execute([':f'=>$u['id'],':t'=>$target]);if($q->fetch()){$pdo->prepare('DELETE FROM follows WHERE follower_id=:f AND following_id=:t')->execute([':f'=>$u['id'],':t'=>$target]);$following=false;}else{$pdo->prepare('INSERT INTO follows(follower_id,following_id,created_at) VALUES(:f,:t,UTC_TIMESTAMP())')->execute([':f'=>$u['id'],':t'=>$target]);$following=true;}respond(['ok'=>true,'data'=>['following'=>$following]]); }
if ($action === 'following_check' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$target=trim((string)($_GET['user_id']??''));$q=$pdo->prepare('SELECT 1 FROM follows WHERE follower_id=:f AND following_id=:t');$q->execute([':f'=>$u['id'],':t'=>$target]);respond(['ok'=>true,'data'=>['following'=>(bool)$q->fetch()]]); }
if ($action === 'search' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$term=trim((string)($_GET['q']??''));if($term==='')respond(['ok'=>true,'data'=>[]]);$like='%'.$term.'%';$q=$pdo->prepare('SELECT id,username,display_name,saki_id,avatar_url,bio,country,gender FROM profiles WHERE id<>:id AND (username LIKE :q OR display_name LIKE :q OR CAST(saki_id AS CHAR)=:exact) ORDER BY username LIMIT 30');$q->execute([':id'=>$u['id'],':q'=>$like,':exact'=>$term]);$rows=$q->fetchAll();respond(['ok'=>true,'data'=>array_map(fn($r)=>$r+['_kind'=>'profile'],$rows)]); }
'''
if marker not in s: raise SystemExit('marker missing')
p.write_text(s.replace(marker,block+'\n'+marker,1)); print('profile features API extended')
