from pathlib import Path
p=Path('/tmp/api.php');s=p.read_text();marker="if ($action === 'room_members' && $_SERVER['REQUEST_METHOD'] === 'GET') {"
block=r'''if ($action === 'family_me' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->prepare('SELECT f.*,fm.role FROM family_members fm JOIN families f ON f.id=fm.family_id WHERE fm.user_id=:u AND fm.status=\'active\' LIMIT 1');$q->execute([':u'=>$u['id']]);$row=$q->fetch();respond(['ok'=>true,'data'=>$row?[$row]:[]]); }
if ($action === 'family_update' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$q=$pdo->prepare('UPDATE families f JOIN family_members fm ON fm.family_id=f.id SET f.name=:n,f.family_alias=:a,f.avatar_url=:av,f.announcement=:an,f.updated_at=UTC_TIMESTAMP() WHERE f.id=:f AND fm.user_id=:u AND fm.role IN (\'owner\',\'admin\')');$q->execute([':n'=>trim((string)($d['name']??'')),':a'=>trim((string)($d['alias']??'')),':av'=>$d['avatar_url']??null,':an'=>$d['announcement']??'',':f'=>$d['family_id']??' ',':u'=>$u['id']]);respond(['ok'=>true]); }
if ($action === 'family_request_decide' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$status=($d['decision']??'reject')==='approve'?'approved':'rejected';$q=$pdo->prepare('SELECT family_id,user_id FROM family_join_requests WHERE id=:id LIMIT 1');$q->execute([':id'=>$d['request_id']??'']);$r=$q->fetch();if(!$r)respond(['ok'=>false,'error'=>'request_not_found'],404);$pdo->beginTransaction();try{$pdo->prepare('UPDATE family_join_requests SET status=:s WHERE id=:id')->execute([':s'=>$status,':id'=>$d['request_id']]);if($status==='approved')$pdo->prepare('INSERT INTO family_members(family_id,user_id,role,status,joined_at) VALUES(:f,:u,\'member\',\'active\',UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE status=\'active\'')->execute([':f'=>$r['family_id'],':u'=>$r['user_id']]);$pdo->commit();respond(['ok'=>true]);}catch(Throwable $e){$pdo->rollBack();respond(['ok'=>false,'error'=>'family_decision_failed'],422);} }
if ($action === 'family_members' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->prepare('SELECT fm.user_id,fm.role,fm.joined_at,p.id,p.username,p.display_name,p.avatar_url,p.saki_id FROM family_members fm JOIN profiles p ON p.id=fm.user_id WHERE fm.family_id=:f AND fm.status=\'active\' ORDER BY fm.joined_at LIMIT 200');$q->execute([':f'=>$_GET['family_id']??'']);respond(['ok'=>true,'data'=>$q->fetchAll()]); }
if ($action === 'family_tasks' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->prepare('SELECT * FROM family_tasks WHERE family_id=:f ORDER BY created_at LIMIT 30');$q->execute([':f'=>$_GET['family_id']??'']);respond(['ok'=>true,'data'=>$q->fetchAll()]); }
if ($action === 'family_task_complete' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$inc=max(1,min(100,(int)($d['increment']??1)));$q=$pdo->prepare('UPDATE family_tasks ft JOIN family_members fm ON fm.family_id=ft.family_id SET ft.progress=LEAST(ft.target,ft.progress+:i) WHERE ft.family_id=:f AND ft.task_key=:k AND fm.user_id=:u AND fm.status=\'active\'');$q->execute([':i'=>$inc,':f'=>$d['family_id']??' ',':k'=>$d['task_key']??' ',':u'=>$u['id']]);$q=$pdo->prepare('SELECT * FROM family_tasks WHERE family_id=:f AND task_key=:k LIMIT 1');$q->execute([':f'=>$d['family_id']??' ',':k'=>$d['task_key']??' ']);respond(['ok'=>true,'data'=>$q->fetch()?:[]]); }
if ($action === 'user_badges' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->prepare('SELECT ub.badge_key,ub.earned_at,bc.name,bc.description,bc.asset_path,bc.sort_order FROM user_badges ub LEFT JOIN badge_catalog bc ON bc.badge_key=ub.badge_key WHERE ub.user_id=:id ORDER BY bc.sort_order,ub.earned_at DESC LIMIT 100');$q->execute([':id'=>$_GET['user_id']??'']);respond(['ok'=>true,'data'=>$q->fetchAll()]); }
if ($action === 'user_vehicles' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->prepare('SELECT i.item_id,i.purchased_at,i.expires_at,i.is_active,c.id,c.name,c.asset_key,c.price_gold_coins,c.duration_days,c.category FROM trace_store_inventory i JOIN trace_store_catalog c ON c.id=i.item_id WHERE i.user_id=:id AND i.is_active=1 ORDER BY i.purchased_at DESC LIMIT 100');$q->execute([':id'=>$_GET['user_id']??'']);respond(['ok'=>true,'data'=>$q->fetchAll()]); }
if ($action === 'user_received_gifts' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->prepare('SELECT rg.gift_id id,g.name,g.icon,g.price,SUM(rg.quantity) received_count,SUM(rg.total_price) received_value,MAX(rg.created_at) last_received_at,MAX(r.name) room_name FROM room_gifts rg JOIN room_gift_catalog g ON g.id=rg.gift_id LEFT JOIN rooms r ON r.id=rg.room_id WHERE rg.recipient_id=:id GROUP BY rg.gift_id,g.name,g.icon,g.price ORDER BY received_value DESC LIMIT 100');$q->execute([':id'=>$_GET['user_id']??'']);respond(['ok'=>true,'data'=>$q->fetchAll()]); }
if ($action === 'user_profile_stats' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$id=trim((string)($_GET['user_id']??''));$q=$pdo->prepare('SELECT (SELECT COUNT(*) FROM posts WHERE author_id=:id) posts,(SELECT COUNT(*) FROM follows WHERE following_id=:id) followers,(SELECT COUNT(*) FROM follows WHERE follower_id=:id) following');$q->execute([':id'=>$id]);$r=$q->fetch();respond(['ok'=>true,'data'=>[['posts'=>(int)$r['posts'],'followers'=>(int)$r['followers'],'following'=>(int)$r['following']]]]); }
if ($action === 'user_profile' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$id=trim((string)($_GET['user_id']??''));$q=$pdo->prepare('SELECT id,username,display_name,saki_id,avatar_url,bio,country,country_code,gender,created_at,vip_level,vip_expires_at,wealth_xp,wealth_level,is_super_admin,admin_role FROM profiles WHERE id=:id LIMIT 1');$q->execute([':id'=>$id]);$row=$q->fetch();respond(['ok'=>true,'data'=>$row?[$row]:[]]); }
if ($action === 'room_ban_check' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->prepare('SELECT expires_at FROM room_bans WHERE room_id=:r AND user_id=:u LIMIT 1');$q->execute([':r'=>$_GET['room_id']??' ',':u'=>$u['id']]);$x=$q->fetch();$banned=$x&&(!$x['expires_at']||strtotime($x['expires_at'])>time());respond(['ok'=>true,'data'=>[['banned'=>$banned,'expires_at'=>$x['expires_at']??null]]]); }
if ($action === 'room_presence' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$room=(string)(body()['room_id']??'');$pdo->prepare('UPDATE room_members SET last_seen=UTC_TIMESTAMP() WHERE room_id=:r AND user_id=:u')->execute([':r'=>$room,':u'=>$u['id']]);respond(['ok'=>true]); }
if ($action === 'seat_claim' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$q=$pdo->prepare('SELECT user_id FROM room_seats WHERE room_id=:r AND seat_no=:s');$q->execute([':r'=>$d['room_id']??' ',':s'=>(int)($d['seat_no']??0)]);$x=$q->fetch();if($x&&$x['user_id']!==$u['id'])respond(['ok'=>false,'error'=>'seat_taken'],409);$pdo->prepare('DELETE FROM room_seats WHERE room_id=:r AND user_id=:u')->execute([':r'=>$d['room_id']??' ',':u'=>$u['id']]);$pdo->prepare('INSERT INTO room_seats(room_id,seat_no,user_id,joined_at,is_speaking) VALUES(:r,:s,:u,UTC_TIMESTAMP(),0) ON DUPLICATE KEY UPDATE user_id=:u,joined_at=UTC_TIMESTAMP()')->execute([':r'=>$d['room_id']??' ',':s'=>(int)($d['seat_no']??0),':u'=>$u['id']]);respond(['ok'=>true]); }
if ($action === 'seat_leave' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$pdo->prepare('DELETE FROM room_seats WHERE room_id=:r AND user_id=:u')->execute([':r'=>body()['room_id']??' ',':u'=>$u['id']]);respond(['ok'=>true]); }
if ($action === 'profile_update' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$q=$pdo->prepare('UPDATE profiles SET username=:n,display_name=:n,bio=:b,country=COALESCE(NULLIF(:c,\'\'),country),country_code=COALESCE(NULLIF(:cc,\'\'),country_code),avatar_url=COALESCE(NULLIF(:a,\'\'),avatar_url),updated_at=UTC_TIMESTAMP() WHERE id=:u');$q->execute([':n'=>trim((string)($d['username']??$u['username'])),':b'=>trim((string)($d['bio']??'')),':c'=>trim((string)($d['country']??'')),':cc'=>trim((string)($d['country_code']??'')),':a'=>trim((string)($d['avatar_url']??'')),':u'=>$u['id']]);respond(['ok'=>true]); }
if ($action === 'country_flag' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$v=trim((string)($_GET['value']??''));$q=$pdo->prepare('SELECT flag FROM countries WHERE name_ar=:v OR code=:c LIMIT 1');$q->execute([':v'=>$v,':c'=>strtoupper($v)]);respond(['ok'=>true,'data'=>[['flag'=>$q->fetchColumn()?:'🌍']]]); }
if ($action === 'content_share' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$table=($d['type']??'post')==='reel'?'reel_shares':'post_shares';$column=$table==='reel_shares'?'reel_id':'post_id';$pdo->prepare("INSERT INTO $table($column,user_id,created_at) VALUES(:id,:u,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE user_id=user_id")->execute([':id'=>$d['id']??' ',':u'=>$u['id']]);respond(['ok'=>true]); }
if ($action === 'room_banners' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->query("SELECT id,image_url,title,sort_order,target_type,target_user_id,target_room_id FROM room_banners WHERE is_active=1 ORDER BY sort_order LIMIT 50");respond(['ok'=>true,'data'=>$q->fetchAll()]); }
'''
if marker not in s:raise SystemExit('marker missing')
s=s.replace(marker,block+marker,1);p.write_text(s);print('social room api extended')
