from pathlib import Path
p=Path('/tmp/api.php'); s=p.read_text(); marker="if ($action === 'google_login' && $_SERVER['REQUEST_METHOD'] === 'POST') {"
block=r'''
if ($action === 'wallet' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->prepare('SELECT wallet_balance,wallet_currency,gold_coins,diamonds,vip_points,wealth_xp,wealth_level,charm_xp,charm_level FROM saki_account_modules WHERE user_id=:u');$q->execute([':u'=>$u['id']]);$r=$q->fetch()?:['wallet_balance'=>0,'wallet_currency'=>'gold','gold_coins'=>0,'diamonds'=>0,'vip_points'=>0,'wealth_xp'=>0,'wealth_level'=>0,'charm_xp'=>0,'charm_level'=>0];respond(['ok'=>true,'data'=>$r]); }
if ($action === 'gift_catalog' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->query('SELECT id,category,name,icon,price,sort_order,is_active,media_url,media_type FROM room_gift_catalog WHERE is_active=1 ORDER BY sort_order LIMIT 100');respond(['ok'=>true,'data'=>$q->fetchAll()]); }
if ($action === 'gift_send' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$room=(string)($d['room_id']??'');$recipient=(string)($d['recipient_id']??'');$gift=(string)($d['gift_id']??'');$qty=max(1,min(100,(int)($d['quantity']??1)));$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT price FROM room_gift_catalog WHERE id=:g AND is_active=1 FOR UPDATE');$q->execute([':g'=>$gift]);$price=$q->fetchColumn();if($price===false)throw new Exception('gift_not_found');$total=(int)$price*$qty;$q=$pdo->prepare('SELECT gold_coins FROM saki_account_modules WHERE user_id=:u FOR UPDATE');$q->execute([':u'=>$u['id']]);$balance=(int)$q->fetchColumn();if($balance<$total)throw new Exception('insufficient_gold_coins');$pdo->prepare('UPDATE saki_account_modules SET gold_coins=gold_coins-:n,updated_at=UTC_TIMESTAMP() WHERE user_id=:u')->execute([':n'=>$total,':u'=>$u['id']]);$id=bin2hex(random_bytes(16));$pdo->prepare('INSERT INTO room_gifts(id,room_id,sender_id,recipient_id,gift_id,quantity,total_price,created_at,recipient_diamonds) VALUES(:id,:r,:s,:to,:g,:q,:p,UTC_TIMESTAMP(),:d)')->execute([':id'=>$id,':r'=>$room,':s'=>$u['id'],':to'=>$recipient,':g'=>$gift,':q'=>$qty,':p'=>$total,':d'=>$total]);$pdo->prepare('INSERT INTO gift_announcements(id,room_id,sender_id,recipient_id,gift_id,total_price,recipient_diamonds,created_at,event_type,multiplier,reward_gold,gift_price) VALUES(:id,:r,:s,:to,:g,:p,:d,UTC_TIMESTAMP(),\'gift\',1,:p,:price)')->execute([':id'=>bin2hex(random_bytes(16)),':r'=>$room,':s'=>$u['id'],':to'=>$recipient,':g'=>$gift,':p'=>$total,':d'=>$total,':price'=>$price]);$pdo->commit();respond(['ok'=>true,'data'=>['id'=>$id,'total_price'=>$total]]);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();respond(['ok'=>false,'error'=>$e->getMessage()],422);} }
'''
if marker not in s: raise SystemExit('marker missing')
p.write_text(s.replace(marker,block+'\n'+marker,1)); print('wallet gifts API extended')
