from pathlib import Path
p=Path('/tmp/api.php');s=p.read_text();marker="if ($action === 'google_login' && $_SERVER['REQUEST_METHOD'] === 'POST') {"
block=r'''
if ($action === 'vip_purchase' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$level=max(1,min(10,(int)(body()['level']??1)));$price=$level*1000;$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT gold_coins FROM saki_account_modules WHERE user_id=:u FOR UPDATE');$q->execute([':u'=>$u['id']]);if((int)$q->fetchColumn()<$price)throw new Exception('insufficient_gold_coins');$pdo->prepare('UPDATE saki_account_modules SET gold_coins=gold_coins-:p,vip_level=:l,updated_at=UTC_TIMESTAMP() WHERE user_id=:u')->execute([':p'=>$price,':l'=>$level,':u'=>$u['id']]);$pdo->prepare('INSERT INTO vip_transactions(id,sender_id,recipient_id,vip_level,price,transaction_type,created_at) VALUES(:id,:s,:r,:l,:p,\'purchase\',UTC_TIMESTAMP())')->execute([':id'=>bin2hex(random_bytes(16)),':s'=>$u['id'],':r'=>$u['id'],':l'=>$level,':p'=>$price]);$pdo->commit();respond(['ok'=>true,'data'=>['vip_level'=>$level,'price'=>$price]]);}catch(Throwable $e){$pdo->rollBack();respond(['ok'=>false,'error'=>$e->getMessage()],422);} }
if ($action === 'diamonds_convert' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$n=max(1,(int)(body()['amount']??0));$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT diamonds FROM saki_account_modules WHERE user_id=:u FOR UPDATE');$q->execute([':u'=>$u['id']]);if((int)$q->fetchColumn()<$n)throw new Exception('insufficient_diamonds');$pdo->prepare('UPDATE saki_account_modules SET diamonds=diamonds-:n,gold_coins=gold_coins+:n,updated_at=UTC_TIMESTAMP() WHERE user_id=:u')->execute([':n'=>$n,':u'=>$u['id']]);$pdo->commit();respond(['ok'=>true,'data'=>['converted'=>$n]]);}catch(Throwable $e){$pdo->rollBack();respond(['ok'=>false,'error'=>$e->getMessage()],422);} }
if ($action === 'redeem' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$code=strtoupper(trim((string)(body()['code']??'')));$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT * FROM saki_redeem_codes WHERE code=:c AND is_active=1 AND expires_at>UTC_TIMESTAMP() AND (max_uses=0 OR used_count<max_uses) FOR UPDATE');$q->execute([':c'=>$code]);$row=$q->fetch();if(!$row)throw new Exception('invalid_or_expired_code');$q=$pdo->prepare('SELECT 1 FROM saki_redeem_code_uses WHERE code_id=:c AND user_id=:u');$q->execute([':c'=>$row['id'],':u'=>$u['id']]);if($q->fetch())throw new Exception('code_already_used');$q=$pdo->prepare('SELECT * FROM saki_redeem_code_rewards WHERE code_id=:c');$q->execute([':c'=>$row['id']]);foreach($q->fetchAll() as $rw){if($rw['reward_type']==='gold')$pdo->prepare('UPDATE saki_account_modules SET gold_coins=gold_coins+:n,updated_at=UTC_TIMESTAMP() WHERE user_id=:u')->execute([':n'=>$rw['quantity'],':u'=>$u['id']]);if($rw['reward_type']==='diamonds')$pdo->prepare('UPDATE saki_account_modules SET diamonds=diamonds+:n,updated_at=UTC_TIMESTAMP() WHERE user_id=:u')->execute([':n'=>$rw['quantity'],':u'=>$u['id']]);}$pdo->prepare('INSERT INTO saki_redeem_code_uses(id,code_id,user_id,redeemed_at) VALUES(:id,:c,:u,UTC_TIMESTAMP())')->execute([':id'=>bin2hex(random_bytes(16)),':c'=>$row['id'],':u'=>$u['id']]);$pdo->prepare('UPDATE saki_redeem_codes SET used_count=used_count+1 WHERE id=:id')->execute([':id'=>$row['id']]);$pdo->commit();respond(['ok'=>true]);}catch(Throwable $e){$pdo->rollBack();respond(['ok'=>false,'error'=>$e->getMessage()],422);} }
if ($action === 'store_products' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->query('SELECT * FROM saki_store_products WHERE is_active=1 ORDER BY created_at DESC LIMIT 100');respond(['ok'=>true,'data'=>$q->fetchAll()]); }
if ($action === 'store_buy' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$id=(string)(body()['product_id']??'');$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT * FROM saki_store_products WHERE id=:id AND is_active=1 FOR UPDATE');$q->execute([':id'=>$id]);$p=$q->fetch();if(!$p)throw new Exception('product_not_found');$q=$pdo->prepare('SELECT gold_coins FROM saki_account_modules WHERE user_id=:u FOR UPDATE');$q->execute([':u'=>$u['id']]);if((int)$q->fetchColumn()<(int)$p['price'])throw new Exception('insufficient_gold_coins');$pdo->prepare('UPDATE saki_account_modules SET gold_coins=gold_coins-:p,updated_at=UTC_TIMESTAMP() WHERE user_id=:u')->execute([':p'=>$p['price'],':u'=>$u['id']]);$pdo->prepare('INSERT INTO saki_store_inventory(user_id,product_id,quantity,equipped,purchased_at,expires_at) VALUES(:u,:p,1,0,UTC_TIMESTAMP(),NULL) ON DUPLICATE KEY UPDATE quantity=quantity+1')->execute([':u'=>$u['id'],':p'=>$id]);$pdo->commit();respond(['ok'=>true]);}catch(Throwable $e){$pdo->rollBack();respond(['ok'=>false,'error'=>$e->getMessage()],422);} }
if ($action === 'admin_add_gold' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u||empty($u['is_super_admin']))respond(['ok'=>false,'error'=>'forbidden'],403);$d=body();$q=$pdo->prepare('UPDATE saki_account_modules SET gold_coins=gold_coins+:n,updated_at=UTC_TIMESTAMP() WHERE user_id=:u');$q->execute([':n'=>(int)$d['amount'],':u'=>$d['user_id']]);respond(['ok'=>true]); }
if ($action === 'recharge_intent' && $_SERVER['REQUEST_METHOD'] === 'POST') { respond(['ok'=>false,'error'=>'payment_provider_not_configured','message'=>'حدد مزود الدفع ومفاتيح API قبل تفعيل الشحن الحقيقي'],501); }
'''
if marker not in s:raise SystemExit('marker missing')
p.write_text(s.replace(marker,block+'\n'+marker,1));print('economy API extended')
