from pathlib import Path
p=Path('/tmp/api.php');s=p.read_text();marker="if ($action === 'google_login' && $_SERVER['REQUEST_METHOD'] === 'POST') {"
block=r'''if ($action === 'families' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->query('SELECT f.*,p.username owner_username,p.avatar_url owner_avatar,(SELECT COUNT(*) FROM family_members fm WHERE fm.family_id=f.id AND fm.status=\'active\') members_count FROM families f JOIN profiles p ON p.id=f.owner_id ORDER BY f.stars DESC LIMIT 100');respond(['ok'=>true,'data'=>$q->fetchAll()]); }
if ($action === 'family_create' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$id=bin2hex(random_bytes(16));$pdo->beginTransaction();try{$pdo->prepare("INSERT INTO families(id,owner_id,name,family_alias,description,avatar_url,created_at,announcement,weekly_starts_at,updated_at) VALUES(:id,:u,:n,:a,:d,:av,UTC_TIMESTAMP(),' ',UTC_TIMESTAMP(),UTC_TIMESTAMP())")->execute([':id'=>$id,':u'=>$u['id'],':n'=>trim($d['name']??''),':a'=>trim($d['alias']??''),':d'=>trim($d['description']??''),':av'=>$d['avatar_url']??null]);$pdo->prepare("INSERT INTO family_members(family_id,user_id,role,status,joined_at) VALUES(:f,:u,'owner','active',UTC_TIMESTAMP())")->execute([':f'=>$id,':u'=>$u['id']]);$pdo->commit();respond(['ok'=>true,'data'=>['id'=>$id,'name'=>$d['name']??'','family_alias'=>$d['alias']??'']]);}catch(Throwable $e){$pdo->rollBack();respond(['ok'=>false,'error'=>$e->getMessage()],422);} }
if ($action === 'family_join' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$pdo->prepare("INSERT INTO family_join_requests(id,family_id,user_id,status,created_at) VALUES(:id,:f,:u,'pending',UTC_TIMESTAMP())")->execute([':id'=>bin2hex(random_bytes(16)),':f'=>$d['family_id']??'',':u'=>$u['id']]);respond(['ok'=>true]); }
if ($action === 'family_leave' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$pdo->prepare("UPDATE family_members SET status='left' WHERE family_id=:f AND user_id=:u")->execute([':f'=>body()['family_id']??' ',':u'=>$u['id']]);respond(['ok'=>true]); }
if ($action === 'family_requests' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->prepare("SELECT r.*,p.username,p.avatar_url,p.saki_id FROM family_join_requests r JOIN profiles p ON p.id=r.user_id WHERE r.family_id=:f AND r.status='pending' ORDER BY r.created_at LIMIT 100");$q->execute([':f'=>$_GET['family_id']??'']);respond(['ok'=>true,'data'=>$q->fetchAll()]); }
'''
if marker not in s:raise SystemExit('marker missing')
p.write_text(s.replace(marker,block+'\n'+marker,1));print('families API extended')
