from pathlib import Path
p=Path('/tmp/api.php');s=p.read_text();marker="if ($action === 'google_login' && $_SERVER['REQUEST_METHOD'] === 'POST') {"
block=r'''
if ($action === 'luck_bag_create' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$total=max(1,(int)($d['total_gold']??0));$limit=max(1,min(100,(int)($d['recipient_limit']??1)));$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT gold_coins FROM saki_account_modules WHERE user_id=:u FOR UPDATE');$q->execute([':u'=>$u['id']]);if((int)$q->fetchColumn()<$total)throw new Exception('insufficient_gold_coins');$pdo->prepare('UPDATE saki_account_modules SET gold_coins=gold_coins-:n,updated_at=UTC_TIMESTAMP() WHERE user_id=:u')->execute([':n'=>$total,':u'=>$u['id']]);$id=bin2hex(random_bytes(16));$pdo->prepare('INSERT INTO room_luck_bags(id,room_id,sender_id,total_gold,recipient_limit,claimed_count,remaining_gold,status,created_at,expires_at) VALUES(:id,:r,:u,:t,:l,0,:t,\'open\',UTC_TIMESTAMP(),DATE_ADD(UTC_TIMESTAMP(),INTERVAL 24 HOUR))')->execute([':id'=>$id,':r'=>$d['room_id'],':u'=>$u['id'],':t'=>$total,':l'=>$limit]);$pdo->commit();respond(['ok'=>true,'data'=>['id'=>$id,'total_gold'=>$total]]);}catch(Throwable $e){$pdo->rollBack();respond(['ok'=>false,'error'=>$e->getMessage()],422);} }
if ($action === 'luck_bag_claim' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$id=(string)(body()['bag_id']??'');$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT * FROM room_luck_bags WHERE id=:id FOR UPDATE');$q->execute([':id'=>$id]);$b=$q->fetch();if(!$b||$b['status']!=='open'||strtotime($b['expires_at'])<time()||$b['remaining_gold']<=0||$b['claimed_count']>=$b['recipient_limit'])throw new Exception('luck_bag_unavailable');$q=$pdo->prepare('SELECT 1 FROM room_luck_bag_claims WHERE bag_id=:b AND user_id=:u');$q->execute([':b'=>$id,':u'=>$u['id']]);if($q->fetch())throw new Exception('already_claimed');$amount=max(1,(int)floor($b['remaining_gold']/($b['recipient_limit']-$b['claimed_count'])));$pdo->prepare('INSERT INTO room_luck_bag_claims(id,bag_id,user_id,amount_gold,claimed_at) VALUES(:id,:b,:u,:n,UTC_TIMESTAMP())')->execute([':id'=>bin2hex(random_bytes(16)),':b'=>$id,':u'=>$u['id'],':n'=>$amount]);$pdo->prepare('UPDATE room_luck_bags SET remaining_gold=remaining_gold-:n,claimed_count=claimed_count+1,status=IF(remaining_gold-:n<=0 OR claimed_count+1>=recipient_limit,\'closed\',\'open\') WHERE id=:id')->execute([':n'=>$amount,':id'=>$id]);$pdo->prepare('UPDATE saki_account_modules SET gold_coins=gold_coins+:n,updated_at=UTC_TIMESTAMP() WHERE user_id=:u')->execute([':n'=>$amount,':u'=>$u['id']]);$pdo->commit();respond(['ok'=>true,'data'=>['amount_gold'=>$amount]]);}catch(Throwable $e){$pdo->rollBack();respond(['ok'=>false,'error'=>$e->getMessage()],422);} }
if ($action === 'global_gifts' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->query('SELECT * FROM gift_announcements ORDER BY created_at DESC LIMIT 100');respond(['ok'=>true,'data'=>$q->fetchAll()]); }
if ($action === 'admin_set_vip' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u||empty($u['is_super_admin']))respond(['ok'=>false,'error'=>'forbidden'],403);$d=body();$q=$pdo->prepare('UPDATE saki_account_modules SET vip_level=:l,updated_at=UTC_TIMESTAMP() WHERE user_id=:u');$q->execute([':l'=>(int)$d['level'],':u'=>$d['user_id']]);respond(['ok'=>true]); }
if ($action === 'admin_add_diamonds' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u||empty($u['is_super_admin']))respond(['ok'=>false,'error'=>'forbidden'],403);$d=body();$q=$pdo->prepare('UPDATE saki_account_modules SET diamonds=diamonds+:n,updated_at=UTC_TIMESTAMP() WHERE user_id=:u');$q->execute([':n'=>(int)$d['amount'],':u'=>$d['user_id']]);respond(['ok'=>true]); }
if ($action === 'store_equip' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$pdo->prepare("UPDATE saki_store_inventory i JOIN saki_store_products p ON p.id=i.product_id SET i.equipped=0 WHERE i.user_id=:u AND p.category=:cat")->execute([':u'=>$u['id'],':cat'=>$d['category']??'frame']);$q=$pdo->prepare('UPDATE saki_store_inventory SET equipped=:e WHERE user_id=:u AND product_id=:p');$q->execute([':e'=>!empty($d['equipped'])?1:0,':u'=>$u['id'],':p'=>$d['product_id']]);respond(['ok'=>true]); }
'''
if marker not in s:raise SystemExit('marker missing')
p.write_text(s.replace(marker,block+'\n'+marker,1));print('luck/global/admin API extended')
