from pathlib import Path
p=Path('/tmp/api.php'); s=p.read_text(); marker="if ($action === 'google_login' && $_SERVER['REQUEST_METHOD'] === 'POST') {"
block=r'''
if ($action === 'rooms_feed' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->query("SELECT r.id,r.room_id,r.owner_id,r.name,r.description,r.country,r.room_type,r.image_url,r.is_active,r.seat_count,r.created_at,p.username,p.avatar_url,p.vip_level,(SELECT COUNT(*) FROM room_members rm WHERE rm.room_id=r.id) member_count FROM rooms r JOIN profiles p ON p.id=r.owner_id ORDER BY r.is_pinned DESC,r.pin_priority DESC,r.created_at DESC LIMIT 100");$rows=$q->fetchAll();foreach($rows as &$r)$r['profiles']=['username'=>$r['username'],'avatar_url'=>$r['avatar_url'],'vip_level'=>(int)$r['vip_level']];respond(['ok'=>true,'data'=>$rows]); }
if ($action === 'room_followed' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->prepare('SELECT room_id FROM room_follows WHERE user_id=:u LIMIT 500');$q->execute([':u'=>$u['id']]);respond(['ok'=>true,'data'=>array_map(fn($r)=>$r['room_id'],$q->fetchAll())]); }
if ($action === 'room_follow_toggle' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$room=trim((string)($d['room_id']??''));$q=$pdo->prepare('SELECT 1 FROM room_follows WHERE room_id=:r AND user_id=:u');$q->execute([':r'=>$room,':u'=>$u['id']]);if($q->fetch()){$pdo->prepare('DELETE FROM room_follows WHERE room_id=:r AND user_id=:u')->execute([':r'=>$room,':u'=>$u['id']]);$f=false;}else{$pdo->prepare('INSERT INTO room_follows(room_id,user_id,created_at) VALUES(:r,:u,UTC_TIMESTAMP())')->execute([':r'=>$room,':u'=>$u['id']]);$f=true;}respond(['ok'=>true,'data'=>['followed'=>$f]]); }
if ($action === 'room_join' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$room=(string)(body()['room_id']??'');$q=$pdo->prepare('INSERT INTO room_members(room_id,user_id,joined_at,last_seen) VALUES(:r,:u,UTC_TIMESTAMP(),UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE last_seen=UTC_TIMESTAMP()');$q->execute([':r'=>$room,':u'=>$u['id']]);respond(['ok'=>true]); }
if ($action === 'room_leave' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$room=(string)(body()['room_id']??'');$pdo->prepare('DELETE FROM room_members WHERE room_id=:r AND user_id=:u')->execute([':r'=>$room,':u'=>$u['id']]);respond(['ok'=>true]); }
if ($action === 'room_create' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$id=bin2hex(random_bytes(16));$code=substr($id,0,12);$q=$pdo->prepare("INSERT INTO rooms(id,room_id,owner_id,name,description,country,room_type,created_at,is_active,category,theme_key,mic_permission) VALUES(:id,:code,:u,:n,:d,:c,:t,UTC_TIMESTAMP(),1,'general','default','all')");$q->execute([':id'=>$id,':code'=>$code,':u'=>$u['id'],':n'=>trim((string)($d['name']??'')),':d'=>trim((string)($d['description']??'')),':c'=>$d['country']??null,':t'=>$d['type']??'public']);$pdo->prepare('INSERT INTO room_members(room_id,user_id,joined_at,last_seen) VALUES(:r,:u,UTC_TIMESTAMP(),UTC_TIMESTAMP())')->execute([':r'=>$id,':u'=>$u['id']]);respond(['ok'=>true,'data'=>['id'=>$id,'room_id'=>$code,'owner_id'=>$u['id'],'name'=>$d['name']??'','description'=>$d['description']??'','country'=>$d['country']??null,'room_type'=>$d['type']??'public','is_active'=>1,'_members_count'=>1]]); }
'''
if marker not in s: raise SystemExit('marker missing')
p.write_text(s.replace(marker,block+'\n'+marker,1)); print('rooms API extended')
