from pathlib import Path
p=Path('/tmp/api.php'); s=p.read_text(); marker="if ($action === 'google_login' && $_SERVER['REQUEST_METHOD'] === 'POST') {"
block=r'''
if ($action === 'conversations' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->prepare("SELECT c.id,c.created_at,c.updated_at FROM conversations c JOIN conversation_members m ON m.conversation_id=c.id WHERE m.user_id=:id ORDER BY c.updated_at DESC LIMIT 100");$q->execute([':id'=>$u['id']]);$rows=$q->fetchAll();foreach($rows as &$r){$m=$pdo->prepare("SELECT p.id,p.username,p.display_name,p.avatar_url,p.saki_id FROM conversation_members cm JOIN profiles p ON p.id=cm.user_id WHERE cm.conversation_id=:cid");$m->execute([':cid'=>$r['id']]);$r['conversation_members']=$m->fetchAll();}$r=null;respond(['ok'=>true,'data'=>$rows]); }
if ($action === 'conversation_create' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$other=trim((string)($d['user_id']??''));if($other===''||$other===$u['id'])respond(['ok'=>false,'error'=>'invalid_user'],422);$q=$pdo->prepare("SELECT c.id FROM conversations c JOIN conversation_members a ON a.conversation_id=c.id AND a.user_id=:me JOIN conversation_members b ON b.conversation_id=c.id AND b.user_id=:other WHERE (SELECT COUNT(*) FROM conversation_members x WHERE x.conversation_id=c.id)=2 LIMIT 1");$q->execute([':me'=>$u['id'],':other'=>$other]);$id=$q->fetchColumn();if(!$id){$id=str_replace('-','',uuid());$pdo->prepare('INSERT INTO conversations(id,created_at,created_by,updated_at) VALUES(:id,UTC_TIMESTAMP(),:u,UTC_TIMESTAMP())')->execute([':id'=>$id,':u'=>$u['id']]);$q=$pdo->prepare('INSERT INTO conversation_members(conversation_id,user_id) VALUES(:c,:u)');$q->execute([':c'=>$id,':u'=>$u['id']]);$q->execute([':c'=>$id,':u'=>$other]);}respond(['ok'=>true,'data'=>['id'=>$id]]); }
if ($action === 'messages' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$cid=trim((string)($_GET['conversation_id']??''));$q=$pdo->prepare('SELECT 1 FROM conversation_members WHERE conversation_id=:c AND user_id=:u');$q->execute([':c'=>$cid,':u'=>$u['id']]);if(!$q->fetch())respond(['ok'=>false,'error'=>'forbidden'],403);$q=$pdo->prepare('SELECT id,conversation_id,sender_id,body,created_at,is_read,message_type,media_url,media_name FROM messages WHERE conversation_id=:c ORDER BY created_at ASC LIMIT 200');$q->execute([':c'=>$cid]);respond(['ok'=>true,'data'=>$q->fetchAll()]); }
if ($action === 'message_send' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$cid=trim((string)($d['conversation_id']??''));$q=$pdo->prepare('SELECT 1 FROM conversation_members WHERE conversation_id=:c AND user_id=:u');$q->execute([':c'=>$cid,':u'=>$u['id']]);if(!$q->fetch())respond(['ok'=>false,'error'=>'forbidden'],403);$id=str_replace('-','',uuid());$q=$pdo->prepare('INSERT INTO messages(id,conversation_id,sender_id,body,created_at,is_read,message_type,media_url,media_name) VALUES(:id,:c,:u,:b,UTC_TIMESTAMP(),0,:t,:url,:name)');$q->execute([':id'=>$id,':c'=>$cid,':u'=>$u['id'],':b'=>trim((string)($d['body']??'')),':t'=>(string)($d['message_type']??'text'),':url'=>$d['media_url']??null,':name'=>$d['media_name']??null]);$pdo->prepare('UPDATE conversations SET updated_at=UTC_TIMESTAMP() WHERE id=:id')->execute([':id'=>$cid]);respond(['ok'=>true,'data'=>['id'=>$id]]); }
if ($action === 'message_react' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$id=str_replace('-','',uuid());$q=$pdo->prepare('INSERT INTO message_reactions(id,message_id,conversation_id,user_id,emoji,created_at) VALUES(:id,:m,:c,:u,:e,UTC_TIMESTAMP())');$q->execute([':id'=>$id,':m'=>$d['message_id'],':c'=>$d['conversation_id'],':u'=>$u['id'],':e'=>$d['emoji']??'❤️']);respond(['ok'=>true]); }
'''
if marker not in s: raise SystemExit('marker missing')
p.write_text(s.replace(marker,block+'\n'+marker,1)); print('messages API extended')
