from pathlib import Path
p=Path('/tmp/api.php');s=p.read_text();marker="if ($action === 'room_members' && $_SERVER['REQUEST_METHOD'] === 'GET') {"
block=r'''if ($action === 'room_ban_check' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->prepare('SELECT expires_at FROM room_bans WHERE room_id=:r AND user_id=:u LIMIT 1');$q->execute([':r'=>$_GET['room_id']??' ',':u'=>$u['id']]);$x=$q->fetch();$banned=$x&&(!$x['expires_at']||strtotime($x['expires_at'])>time());respond(['ok'=>true,'data'=>[['banned'=>$banned,'expires_at'=>$x['expires_at']??null]]]); }
if ($action === 'room_presence' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$room=(string)(body()['room_id']??'');$pdo->prepare('UPDATE room_members SET last_seen=UTC_TIMESTAMP() WHERE room_id=:r AND user_id=:u')->execute([':r'=>$room,':u'=>$u['id']]);respond(['ok'=>true]); }
if ($action === 'seat_claim' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$q=$pdo->prepare('SELECT user_id FROM room_seats WHERE room_id=:r AND seat_no=:s');$q->execute([':r'=>$d['room_id']??' ',':s'=>(int)($d['seat_no']??0)]);$x=$q->fetch();if($x&&$x['user_id']!==$u['id'])respond(['ok'=>false,'error'=>'seat_taken'],409);$pdo->prepare('DELETE FROM room_seats WHERE room_id=:r AND user_id=:u')->execute([':r'=>$d['room_id']??' ',':u'=>$u['id']]);$pdo->prepare('INSERT INTO room_seats(room_id,seat_no,user_id,joined_at,is_speaking) VALUES(:r,:s,:u,UTC_TIMESTAMP(),0) ON DUPLICATE KEY UPDATE user_id=:u,joined_at=UTC_TIMESTAMP()')->execute([':r'=>$d['room_id']??' ',':s'=>(int)($d['seat_no']??0),':u'=>$u['id']]);respond(['ok'=>true]); }
if ($action === 'seat_leave' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$pdo->prepare('DELETE FROM room_seats WHERE room_id=:r AND user_id=:u')->execute([':r'=>body()['room_id']??' ',':u'=>$u['id']]);respond(['ok'=>true]); }
if ($action === 'profile_update' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$q=$pdo->prepare('UPDATE profiles SET username=:n,display_name=:n,bio=:b,country=COALESCE(NULLIF(:c,\'\'),country),country_code=COALESCE(NULLIF(:cc,\'\'),country_code),avatar_url=COALESCE(NULLIF(:a,\'\'),avatar_url),updated_at=UTC_TIMESTAMP() WHERE id=:u');$q->execute([':n'=>trim((string)($d['username']??$u['username'])),':b'=>trim((string)($d['bio']??'')),':c'=>trim((string)($d['country']??'')),':cc'=>trim((string)($d['country_code']??'')),':a'=>trim((string)($d['avatar_url']??'')),':u'=>$u['id']]);respond(['ok'=>true]); }
if ($action === 'country_flag' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$v=trim((string)($_GET['value']??''));$q=$pdo->prepare('SELECT flag FROM countries WHERE name_ar=:v OR code=:c LIMIT 1');$q->execute([':v'=>$v,':c'=>strtoupper($v)]);respond(['ok'=>true,'data'=>[['flag'=>$q->fetchColumn()?:'🌍']]]); }
if ($action === 'content_share' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$table=($d['type']??'post')==='reel'?'reel_shares':'post_shares';$column=$table==='reel_shares'?'reel_id':'post_id';$pdo->prepare("INSERT INTO $table($column,user_id,created_at) VALUES(:id,:u,UTC_TIMESTAMP()) ON DUPLICATE KEY UPDATE user_id=user_id")->execute([':id'=>$d['id']??' ',':u'=>$u['id']]);respond(['ok'=>true]); }
if ($action === 'room_banners' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->query("SELECT id,image_url,title,sort_order,target_type,target_user_id,target_room_id FROM room_banners WHERE is_active=1 ORDER BY sort_order LIMIT 50");respond(['ok'=>true,'data'=>$q->fetchAll()]); }
'''
if marker not in s:raise SystemExit('marker missing')
s=s.replace(marker,block+marker,1);p.write_text(s);print('social room api extended')
