from pathlib import Path
p=Path('/tmp/api.php');s=p.read_text();marker="if ($action === 'google_login' && $_SERVER['REQUEST_METHOD'] === 'POST') {"
block=r'''if ($action === 'reels_feed' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->query("SELECT r.id,r.author_id,r.video_url,r.description,r.visibility,r.created_at,p.username,p.avatar_url,p.saki_id,p.vip_level,p.wealth_level,(SELECT COUNT(*) FROM reel_likes l WHERE l.reel_id=r.id) likes_count,(SELECT COUNT(*) FROM reel_comments c WHERE c.reel_id=r.id) comments_count FROM reels r JOIN profiles p ON p.id=r.author_id ORDER BY r.created_at DESC LIMIT 50");respond(['ok'=>true,'data'=>$q->fetchAll()]); }
if ($action === 'reel_like_toggle' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$id=(string)(body()['reel_id']??'');$q=$pdo->prepare('SELECT 1 FROM reel_likes WHERE reel_id=:r AND user_id=:u');$q->execute([':r'=>$id,':u'=>$u['id']]);if($q->fetch()){$pdo->prepare('DELETE FROM reel_likes WHERE reel_id=:r AND user_id=:u')->execute([':r'=>$id,':u'=>$u['id']]);$liked=false;}else{$pdo->prepare('INSERT INTO reel_likes(reel_id,user_id,created_at) VALUES(:r,:u,UTC_TIMESTAMP())')->execute([':r'=>$id,':u'=>$u['id']]);$liked=true;}respond(['ok'=>true,'data'=>['liked'=>$liked]]); }
if ($action === 'reel_comments' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->prepare('SELECT c.id,c.content,c.created_at,c.user_id,p.username,p.avatar_url,p.vip_level FROM reel_comments c JOIN profiles p ON p.id=c.user_id WHERE c.reel_id=:r ORDER BY c.created_at LIMIT 200');$q->execute([':r'=>$_GET['reel_id']??'']);respond(['ok'=>true,'data'=>$q->fetchAll()]); }
if ($action === 'reel_comment_create' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$q=$pdo->prepare('INSERT INTO reel_comments(id,reel_id,user_id,content,created_at) VALUES(:id,:r,:u,:c,UTC_TIMESTAMP())');$q->execute([':id'=>bin2hex(random_bytes(16)),':r'=>$d['reel_id']??'',':u'=>$u['id'],':c'=>trim((string)($d['content']??''))]);respond(['ok'=>true]); }
'''
if marker not in s:raise SystemExit('marker missing')
p.write_text(s.replace(marker,block+'\n'+marker,1));print('reels API extended')
