from pathlib import Path
p=Path('/tmp/api.php');s=p.read_text();marker="if ($action === 'google_login' && $_SERVER['REQUEST_METHOD'] === 'POST') {"
block=r'''if ($action === 'notifications' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->prepare('SELECT n.*,p.username,p.display_name,p.avatar_url,p.saki_id,p.vip_level FROM notifications n LEFT JOIN profiles p ON p.id=n.actor_id WHERE n.user_id=:u ORDER BY n.created_at DESC LIMIT 200');$q->execute([':u'=>$u['id']]);respond(['ok'=>true,'data'=>$q->fetchAll()]); }
if ($action === 'notifications_read' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$type=body()['type']??null;$sql='UPDATE notifications SET is_read=1 WHERE user_id=:u';$params=[':u'=>$u['id']];if($type){$sql.=' AND type=:t';$params[':t']=$type;}$pdo->prepare($sql)->execute($params);respond(['ok'=>true]); }
if ($action === 'room_messages' && $_SERVER['REQUEST_METHOD'] === 'GET') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$q=$pdo->prepare('SELECT m.*,p.username,p.display_name,p.avatar_url,p.vip_level FROM room_messages m LEFT JOIN profiles p ON p.id=m.sender_id WHERE m.room_id=:r ORDER BY m.created_at DESC LIMIT 100');$q->execute([':r'=>$_GET['room_id']??'']);$rows=array_reverse($q->fetchAll());respond(['ok'=>true,'data'=>$rows]); }
if ($action === 'room_message_send' && $_SERVER['REQUEST_METHOD'] === 'POST') { $u=currentUser($pdo);if(!$u)respond(['ok'=>false,'error'=>'unauthorized'],401);$d=body();$room=(string)($d['room_id']??'');$q=$pdo->prepare('SELECT mute_chat,expires_at FROM room_mutes WHERE room_id=:r AND user_id=:u');$q->execute([':r'=>$room,':u'=>$u['id']]);$m=$q->fetch();if($m&&$m['mute_chat']&&(empty($m['expires_at'])||strtotime($m['expires_at'])>time()))respond(['ok'=>false,'error'=>'muted'],403);$pdo->prepare('INSERT INTO room_messages(id,room_id,sender_id,body,created_at,message_type,payload) VALUES(:id,:r,:u,:b,UTC_TIMESTAMP(),:t,:p)')->execute([':id'=>bin2hex(random_bytes(16)),':r'=>$room,':u'=>$u['id'],':b'=>trim((string)($d['body']??'')),':t'=>$d['type']??'chat',':p'=>json_encode($d['payload']??[]) ]);respond(['ok'=>true]); }
'''
if marker not in s:raise SystemExit('marker missing')
p.write_text(s.replace(marker,block+'\n'+marker,1));print('notifications room chat API extended')
