-- Secure room-game RPCs: every wager is authenticated, membership-checked, and charged atomically.

create table if not exists public.saki_wheel_rounds (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  round_no bigint not null,
  status text not null default 'betting' check (status in ('betting','result','settled')),
  betting_ends_at timestamptz not null,
  result_ends_at timestamptz not null,
  winning_food text,
  created_at timestamptz not null default now(),
  unique(room_id, round_no)
);
create table if not exists public.saki_wheel_bets (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.saki_wheel_rounds(id) on delete cascade,
  room_id uuid not null references public.rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  food_key text not null,
  amount bigint not null check (amount > 0),
  created_at timestamptz not null default now()
);
create index if not exists saki_wheel_round_room_idx on public.saki_wheel_rounds(room_id, created_at desc);
create index if not exists saki_wheel_bet_round_user_idx on public.saki_wheel_bets(round_id, user_id, food_key);
alter table public.saki_wheel_rounds enable row level security;
alter table public.saki_wheel_bets enable row level security;
drop policy if exists wheel_round_read on public.saki_wheel_rounds;
create policy wheel_round_read on public.saki_wheel_rounds for select to authenticated using (true);
drop policy if exists wheel_bet_read on public.saki_wheel_bets;
create policy wheel_bet_read on public.saki_wheel_bets for select to authenticated using (user_id = auth.uid() or public.is_saki_super_admin());

create or replace function public.saki_wheel_current_round(p_room_id uuid)
returns public.saki_wheel_rounds language plpgsql security definer set search_path=public as $func$
declare r public.saki_wheel_rounds; n bigint;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  if not exists(select 1 from public.rooms rm where rm.id=p_room_id and coalesce(rm.is_active,true)) then raise exception 'game_room_not_available'; end if;
  if not exists(select 1 from public.room_members m where m.room_id=p_room_id and m.user_id=auth.uid())
     and not exists(select 1 from public.rooms rm where rm.id=p_room_id and rm.owner_id=auth.uid()) then raise exception 'not_room_member'; end if;
  update public.saki_wheel_rounds set status='settled' where room_id=p_room_id and status='result' and result_ends_at<=now();
  select * into r from public.saki_wheel_rounds where room_id=p_room_id and status in ('betting','result') order by id desc limit 1;
  if r.id is not null then return r; end if;
  select coalesce(max(round_no),0)+1 into n from public.saki_wheel_rounds where room_id=p_room_id;
  insert into public.saki_wheel_rounds(room_id,round_no,status,betting_ends_at,result_ends_at)
  values(p_room_id,n,'betting',now()+interval '15 seconds',now()+interval '25 seconds')
  on conflict(room_id,round_no) do nothing;
  select * into r from public.saki_wheel_rounds where room_id=p_room_id order by id desc limit 1;
  return r;
end;
$func$;

create or replace function public.saki_wheel_place_bet(p_room_id uuid,p_food_key text,p_amount bigint)
returns table(round_id bigint,food_key text,amount bigint,gold_coins bigint)
language plpgsql security definer set search_path=public as $func$
declare r public.saki_wheel_rounds; balance bigint;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  if not exists(select 1 from public.room_members m where m.room_id=p_room_id and m.user_id=auth.uid())
     and not exists(select 1 from public.rooms rm where rm.id=p_room_id and rm.owner_id=auth.uid()) then raise exception 'not_room_member'; end if;
  if p_amount not in (10,100,1000,10000,100000) then raise exception 'invalid_wheel_amount'; end if;
  if p_food_key not in ('tomato','burger','cake','pizza','shrimp','ice_cream','orange','corn','carrot') then raise exception 'invalid_wheel_food'; end if;
  select * into r from public.saki_wheel_current_round(p_room_id);
  if r.status <> 'betting' or now() >= r.betting_ends_at then raise exception 'wheel_betting_closed'; end if;
  update public.saki_account_modules m set gold_coins=m.gold_coins-p_amount,updated_at=now()
    where m.user_id=auth.uid() and m.gold_coins>=p_amount;
  if not found then raise exception 'insufficient_gold'; end if;
  insert into public.saki_wheel_bets(round_id,room_id,user_id,food_key,amount)
    values(r.id,p_room_id,auth.uid(),p_food_key,p_amount);
  select m.gold_coins into balance from public.saki_account_modules m where m.user_id=auth.uid();
  return query select r.id,p_food_key,p_amount,balance;
end;
$func$;

create or replace function public.saki_wheel_resolve(p_round_id bigint)
returns public.saki_wheel_rounds language plpgsql security definer set search_path=public as $func$
declare r public.saki_wheel_rounds; pick double precision; winner text; payout record;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  select * into r from public.saki_wheel_rounds where id=p_round_id for update;
  if r.id is null then raise exception 'round_not_found'; end if;
  if not exists(select 1 from public.room_members m where m.room_id=r.room_id and m.user_id=auth.uid())
     and not exists(select 1 from public.rooms rm where rm.id=r.room_id and rm.owner_id=auth.uid()) then raise exception 'not_room_member'; end if;
  if r.status='settled' then return r; end if;
  if now()<r.betting_ends_at then raise exception 'wheel_betting_not_finished'; end if;
  if r.status='betting' then
    pick:=random();
    winner:=case when pick<.03 then 'burger' when pick<.08 then 'tomato' when pick<.18 then 'cake' when pick<.33 then 'pizza' when pick<.43 then 'shrimp' when pick<.55 then 'ice_cream' when pick<.70 then 'orange' when pick<.85 then 'corn' else 'carrot' end;
    update public.saki_wheel_rounds set status='result',winning_food=winner where id=r.id returning * into r;
    for payout in select user_id,sum(amount)::bigint as total from public.saki_wheel_bets where round_id=r.id and food_key=winner group by user_id loop
      update public.saki_account_modules m
      set gold_coins=m.gold_coins+(payout.total*case winner when 'burger' then 45 when 'tomato' then 100 when 'cake' then 25 when 'pizza' then 15 when 'shrimp' then 10 when 'ice_cream' then 7 when 'orange' then 5 when 'corn' then 5 else 3 end),updated_at=now()
      where m.user_id=payout.user_id;
    end loop;
  end if;
  if now()>=r.result_ends_at then update public.saki_wheel_rounds set status='settled' where id=r.id returning * into r; end if;
  return r;
end;
$func$;

create table if not exists public.saki_gold_reel_spins (
  id bigint generated always as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  wager bigint not null check (wager > 0),
  symbols jsonb not null,
  payout bigint not null default 0,
  created_at timestamptz not null default now()
);
alter table public.saki_gold_reel_spins enable row level security;
drop policy if exists saki_gold_reel_spins_self on public.saki_gold_reel_spins;
create policy saki_gold_reel_spins_self on public.saki_gold_reel_spins for select to authenticated using(user_id=auth.uid());
create index if not exists saki_gold_reel_spins_user_created_idx on public.saki_gold_reel_spins(user_id,created_at desc);

create or replace function public.saki_gold_reels_spin(p_room_id uuid,p_wager bigint)
returns table(spin_id bigint,symbols jsonb,payout bigint,gold_coins bigint)
language plpgsql security definer set search_path=public as $func$
declare
  v_symbols text[]:=array['diamond','ruby','sapphire','crown','chest','coin'];
  v_grid text[]:=array[]::text[]; v_symbol text; v_count integer; v_payout bigint:=0;
  v_balance bigint; v_id bigint; i integer;
begin
  if auth.uid() is null then raise exception 'not_authenticated'; end if;
  if p_room_id is null or not exists(select 1 from public.rooms rm where rm.id=p_room_id and coalesce(rm.is_active,false)) then raise exception 'game_room_not_available'; end if;
  if not exists(select 1 from public.room_members m where m.room_id=p_room_id and m.user_id=auth.uid())
     and not exists(select 1 from public.rooms rm where rm.id=p_room_id and rm.owner_id=auth.uid()) then raise exception 'not_room_member'; end if;
  if p_wager not in(10,50,100,500,1000,5000,10000) then raise exception 'invalid_reels_wager'; end if;
  update public.saki_account_modules m set gold_coins=m.gold_coins-p_wager,updated_at=now() where m.user_id=auth.uid() and m.gold_coins>=p_wager;
  if not found then raise exception 'insufficient_gold'; end if;
  for i in 1..15 loop v_grid:=array_append(v_grid,v_symbols[1+floor(random()*array_length(v_symbols,1))::int]); end loop;
  foreach v_symbol in array v_symbols loop
    select count(*) into v_count from unnest(v_grid) as x where x=v_symbol;
    if v_count>=5 then v_payout:=greatest(v_payout,p_wager*25);
    elsif v_count>=4 then v_payout:=greatest(v_payout,p_wager*8);
    elsif v_count>=3 then v_payout:=greatest(v_payout,p_wager*2);
    end if;
  end loop;
  if v_grid[1]='chest' and v_grid[5]='chest' and v_grid[9]='chest' then v_payout:=v_payout+p_wager*10; end if;
  insert into public.saki_gold_reel_spins(room_id,user_id,wager,symbols,payout) values(p_room_id,auth.uid(),p_wager,to_jsonb(v_grid),v_payout) returning id into v_id;
  if v_payout>0 then update public.saki_account_modules m set gold_coins=m.gold_coins+v_payout,updated_at=now() where m.user_id=auth.uid(); end if;
  select m.gold_coins into v_balance from public.saki_account_modules m where m.user_id=auth.uid();
  return query select v_id,to_jsonb(v_grid),v_payout,coalesce(v_balance,0);
end;
$func$;

DO $$ BEGIN
  IF NOT EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='saki_wheel_rounds') THEN ALTER PUBLICATION supabase_realtime ADD TABLE public.saki_wheel_rounds; END IF;
  IF NOT EXISTS(SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename='saki_wheel_bets') THEN ALTER PUBLICATION supabase_realtime ADD TABLE public.saki_wheel_bets; END IF;
END $$;
REVOKE ALL ON FUNCTION public.saki_wheel_current_round(uuid),public.saki_wheel_place_bet(uuid,text,bigint),public.saki_wheel_resolve(bigint),public.saki_gold_reels_spin(uuid,bigint) FROM public;
GRANT EXECUTE ON FUNCTION public.saki_wheel_current_round(uuid),public.saki_wheel_place_bet(uuid,text,bigint),public.saki_wheel_resolve(bigint),public.saki_gold_reels_spin(uuid,bigint) TO authenticated;
