-- SAKI animated room gift catalog expansion.
-- Media paths point to bundled Flutter assets; the app renders them locally.
-- Asset sources and licenses are documented in EMOJI_EFFECTS_SOURCES.md.

alter table public.room_gift_catalog
  add column if not exists media_url text,
  add column if not exists media_type text not null default 'emoji',
  add column if not exists duration_seconds integer not null default 10,
  add column if not exists thumbnail_url text;

create unique index if not exists room_gift_catalog_category_name_uidx
  on public.room_gift_catalog(category, name);

insert into public.room_gift_catalog
  (gift_type, display_name, category, price, emoji, name, icon, sort_order,
   media_url, media_type, duration_seconds, thumbnail_url, is_active)
values
  ('saki_general_01','وردة ذهبية','general',100,'🎁','وردة ذهبية','assets/rooms/gifts/general/general_01.gif',101,'assets/rooms/gifts/general/general_01.gif','gif',10,'assets/rooms/gifts/general/general_01.gif',true),
  ('saki_general_02','قلب لامع','general',200,'🎁','قلب لامع','assets/rooms/gifts/general/general_02.gif',102,'assets/rooms/gifts/general/general_02.gif','gif',10,'assets/rooms/gifts/general/general_02.gif',true),
  ('saki_general_03','تاج ملكي','general',300,'🎁','تاج ملكي','assets/rooms/gifts/general/general_03.gif',103,'assets/rooms/gifts/general/general_03.gif','gif',10,'assets/rooms/gifts/general/general_03.gif',true),
  ('saki_general_04','نجمة مضيئة','general',400,'🎁','نجمة مضيئة','assets/rooms/gifts/general/general_04.gif',104,'assets/rooms/gifts/general/general_04.gif','gif',10,'assets/rooms/gifts/general/general_04.gif',true),
  ('saki_general_05','ماسة زرقاء','general',500,'🎁','ماسة زرقاء','assets/rooms/gifts/general/general_05.gif',105,'assets/rooms/gifts/general/general_05.gif','gif',10,'assets/rooms/gifts/general/general_05.gif',true),
  ('saki_general_06','فراشة حب','general',600,'🎁','فراشة حب','assets/rooms/gifts/general/general_06.gif',106,'assets/rooms/gifts/general/general_06.gif','gif',10,'assets/rooms/gifts/general/general_06.gif',true),
  ('saki_general_07','قمر فضي','general',700,'🎁','قمر فضي','assets/rooms/gifts/general/general_07.gif',107,'assets/rooms/gifts/general/general_07.gif','gif',10,'assets/rooms/gifts/general/general_07.gif',true),
  ('saki_general_08','شمس ذهبية','general',800,'🎁','شمس ذهبية','assets/rooms/gifts/general/general_08.gif',108,'assets/rooms/gifts/general/general_08.gif','gif',10,'assets/rooms/gifts/general/general_08.gif',true),
  ('saki_general_09','بالون فرح','general',900,'🎁','بالون فرح','assets/rooms/gifts/general/general_09.gif',109,'assets/rooms/gifts/general/general_09.gif','gif',10,'assets/rooms/gifts/general/general_09.gif',true),
  ('saki_general_10','كعكة احتفال','general',1000,'🎁','كعكة احتفال','assets/rooms/gifts/general/general_10.gif',110,'assets/rooms/gifts/general/general_10.gif','gif',10,'assets/rooms/gifts/general/general_10.gif',true),
  ('saki_general_11','هدية مفاجأة','general',1100,'🎁','هدية مفاجأة','assets/rooms/gifts/general/general_11.gif',111,'assets/rooms/gifts/general/general_11.gif','gif',10,'assets/rooms/gifts/general/general_11.gif',true),
  ('saki_general_12','صاروخ نجاح','general',1200,'🎁','صاروخ نجاح','assets/rooms/gifts/general/general_12.gif',112,'assets/rooms/gifts/general/general_12.gif','gif',10,'assets/rooms/gifts/general/general_12.gif',true),
  ('saki_general_13','كأس فوز','general',1300,'🎁','كأس فوز','assets/rooms/gifts/general/general_13.gif',113,'assets/rooms/gifts/general/general_13.gif','gif',10,'assets/rooms/gifts/general/general_13.gif',true),
  ('saki_general_14','ميدالية ذهبية','general',1400,'🎁','ميدالية ذهبية','assets/rooms/gifts/general/general_14.gif',114,'assets/rooms/gifts/general/general_14.gif','gif',10,'assets/rooms/gifts/general/general_14.gif',true),
  ('saki_general_15','نجمة حظ','general',1500,'🎁','نجمة حظ','assets/rooms/gifts/general/general_15.gif',115,'assets/rooms/gifts/general/general_15.gif','gif',10,'assets/rooms/gifts/general/general_15.gif',true),
  ('saki_general_16','سحابة قلوب','general',1600,'🎁','سحابة قلوب','assets/rooms/gifts/general/general_16.gif',116,'assets/rooms/gifts/general/general_16.gif','gif',10,'assets/rooms/gifts/general/general_16.gif',true),
  ('saki_general_17','مطر قلوب','general',1700,'🎁','مطر قلوب','assets/rooms/gifts/general/general_17.gif',117,'assets/rooms/gifts/general/general_17.gif','gif',10,'assets/rooms/gifts/general/general_17.gif',true),
  ('saki_general_18','قوس قزح','general',1800,'🎁','قوس قزح','assets/rooms/gifts/general/general_18.gif',118,'assets/rooms/gifts/general/general_18.gif','gif',10,'assets/rooms/gifts/general/general_18.gif',true),
  ('saki_general_19','ألعاب نارية','general',1900,'🎁','ألعاب نارية','assets/rooms/gifts/general/general_19.gif',119,'assets/rooms/gifts/general/general_19.gif','gif',10,'assets/rooms/gifts/general/general_19.gif',true),
  ('saki_general_20','كرة ضوء','general',2000,'🎁','كرة ضوء','assets/rooms/gifts/general/general_20.gif',120,'assets/rooms/gifts/general/general_20.gif','gif',10,'assets/rooms/gifts/general/general_20.gif',true),
  ('saki_general_21','ميكروفون لامع','general',2100,'🎁','ميكروفون لامع','assets/rooms/gifts/general/general_21.gif',121,'assets/rooms/gifts/general/general_21.gif','gif',10,'assets/rooms/gifts/general/general_21.gif',true),
  ('saki_general_22','غيتار احتفال','general',2200,'🎁','غيتار احتفال','assets/rooms/gifts/general/general_22.gif',122,'assets/rooms/gifts/general/general_22.gif','gif',10,'assets/rooms/gifts/general/general_22.gif',true),
  ('saki_general_23','طبلة فرح','general',2300,'🎁','طبلة فرح','assets/rooms/gifts/general/general_23.gif',123,'assets/rooms/gifts/general/general_23.gif','gif',10,'assets/rooms/gifts/general/general_23.gif',true),
  ('saki_general_24','تذكرة حفلة','general',2400,'🎁','تذكرة حفلة','assets/rooms/gifts/general/general_24.gif',124,'assets/rooms/gifts/general/general_24.gif','gif',10,'assets/rooms/gifts/general/general_24.gif',true),
  ('saki_general_25','كرة ذهبية','general',2500,'🎁','كرة ذهبية','assets/rooms/gifts/general/general_25.gif',125,'assets/rooms/gifts/general/general_25.gif','gif',10,'assets/rooms/gifts/general/general_25.gif',true),
  ('saki_general_26','طائرة حب','general',2600,'🎁','طائرة حب','assets/rooms/gifts/general/general_26.gif',126,'assets/rooms/gifts/general/general_26.gif','gif',10,'assets/rooms/gifts/general/general_26.gif',true),
  ('saki_general_27','سيارة فاخرة','general',2700,'🎁','سيارة فاخرة','assets/rooms/gifts/general/general_27.gif',127,'assets/rooms/gifts/general/general_27.gif','gif',10,'assets/rooms/gifts/general/general_27.gif',true),
  ('saki_general_28','يخت ملكي','general',2800,'🎁','يخت ملكي','assets/rooms/gifts/general/general_28.gif',128,'assets/rooms/gifts/general/general_28.gif','gif',10,'assets/rooms/gifts/general/general_28.gif',true),
  ('saki_general_29','قصر الأحلام','general',2900,'🎁','قصر الأحلام','assets/rooms/gifts/general/general_29.gif',129,'assets/rooms/gifts/general/general_29.gif','gif',10,'assets/rooms/gifts/general/general_29.gif',true),
  ('saki_general_30','مصباح سحري','general',3000,'🎁','مصباح سحري','assets/rooms/gifts/general/general_30.gif',130,'assets/rooms/gifts/general/general_30.gif','gif',10,'assets/rooms/gifts/general/general_30.gif',true),
  ('saki_general_31','صندوق كنز','general',3100,'🎁','صندوق كنز','assets/rooms/gifts/general/general_31.gif',131,'assets/rooms/gifts/general/general_31.gif','gif',10,'assets/rooms/gifts/general/general_31.gif',true),
  ('saki_general_32','حصان ذهبي','general',3200,'🎁','حصان ذهبي','assets/rooms/gifts/general/general_32.gif',132,'assets/rooms/gifts/general/general_32.gif','gif',10,'assets/rooms/gifts/general/general_32.gif',true),
  ('saki_general_33','أسد ملكي','general',3300,'🎁','أسد ملكي','assets/rooms/gifts/general/general_33.gif',133,'assets/rooms/gifts/general/general_33.gif','gif',10,'assets/rooms/gifts/general/general_33.gif',true),
  ('saki_general_34','تنين لامع','general',3400,'🎁','تنين لامع','assets/rooms/gifts/general/general_34.gif',134,'assets/rooms/gifts/general/general_34.gif','gif',10,'assets/rooms/gifts/general/general_34.gif',true),
  ('saki_general_35','روبوت مرح','general',3500,'🎁','روبوت مرح','assets/rooms/gifts/general/general_35.gif',135,'assets/rooms/gifts/general/general_35.gif','gif',10,'assets/rooms/gifts/general/general_35.gif',true),
  ('saki_general_36','قط لطيف','general',3600,'🎁','قط لطيف','assets/rooms/gifts/general/general_36.gif',136,'assets/rooms/gifts/general/general_36.gif','gif',10,'assets/rooms/gifts/general/general_36.gif',true),
  ('saki_general_37','كلب وفاء','general',3700,'🎁','كلب وفاء','assets/rooms/gifts/general/general_37.gif',137,'assets/rooms/gifts/general/general_37.gif','gif',10,'assets/rooms/gifts/general/general_37.gif',true),
  ('saki_general_38','باندا حب','general',3800,'🎁','باندا حب','assets/rooms/gifts/general/general_38.gif',138,'assets/rooms/gifts/general/general_38.gif','gif',10,'assets/rooms/gifts/general/general_38.gif',true),
  ('saki_general_39','أرنب وردي','general',3900,'🎁','أرنب وردي','assets/rooms/gifts/general/general_39.gif',139,'assets/rooms/gifts/general/general_39.gif','gif',10,'assets/rooms/gifts/general/general_39.gif',true),
  ('saki_general_40','دب دافئ','general',4000,'🎁','دب دافئ','assets/rooms/gifts/general/general_40.gif',140,'assets/rooms/gifts/general/general_40.gif','gif',10,'assets/rooms/gifts/general/general_40.gif',true),
  ('saki_general_41','قلب كريستال','general',4100,'🎁','قلب كريستال','assets/rooms/gifts/general/general_41.gif',141,'assets/rooms/gifts/general/general_41.gif','gif',10,'assets/rooms/gifts/general/general_41.gif',true),
  ('saki_general_42','إكليل ورد','general',4200,'🎁','إكليل ورد','assets/rooms/gifts/general/general_42.gif',142,'assets/rooms/gifts/general/general_42.gif','gif',10,'assets/rooms/gifts/general/general_42.gif',true),
  ('saki_general_43','شجرة أمنيات','general',4300,'🎁','شجرة أمنيات','assets/rooms/gifts/general/general_43.gif',143,'assets/rooms/gifts/general/general_43.gif','gif',10,'assets/rooms/gifts/general/general_43.gif',true),
  ('saki_general_44','كوكب لامع','general',4400,'🎁','كوكب لامع','assets/rooms/gifts/general/general_44.gif',144,'assets/rooms/gifts/general/general_44.gif','gif',10,'assets/rooms/gifts/general/general_44.gif',true),
  ('saki_general_45','مجرة حب','general',4500,'🎁','مجرة حب','assets/rooms/gifts/general/general_45.gif',145,'assets/rooms/gifts/general/general_45.gif','gif',10,'assets/rooms/gifts/general/general_45.gif',true),
  ('saki_cp_01','قبلة وردية','cp',500,'💗','قبلة وردية','assets/rooms/gifts/cp/cp_01.gif',201,'assets/rooms/gifts/cp/cp_01.gif','gif',10,'assets/rooms/gifts/cp/cp_01.gif',true),
  ('saki_cp_02','رسالة حب','cp',1000,'💗','رسالة حب','assets/rooms/gifts/cp/cp_02.gif',202,'assets/rooms/gifts/cp/cp_02.gif','gif',10,'assets/rooms/gifts/cp/cp_02.gif',true),
  ('saki_cp_03','خاتم ألماس','cp',1500,'💗','خاتم ألماس','assets/rooms/gifts/cp/cp_03.gif',203,'assets/rooms/gifts/cp/cp_03.gif','gif',10,'assets/rooms/gifts/cp/cp_03.gif',true),
  ('saki_cp_04','قلوب متشابكة','cp',2000,'💗','قلوب متشابكة','assets/rooms/gifts/cp/cp_04.gif',204,'assets/rooms/gifts/cp/cp_04.gif','gif',10,'assets/rooms/gifts/cp/cp_04.gif',true),
  ('saki_cp_05','دب عاشق','cp',2500,'💗','دب عاشق','assets/rooms/gifts/cp/cp_05.gif',205,'assets/rooms/gifts/cp/cp_05.gif','gif',10,'assets/rooms/gifts/cp/cp_05.gif',true),
  ('saki_cp_06','وردة حمراء','cp',3000,'💗','وردة حمراء','assets/rooms/gifts/cp/cp_06.gif',206,'assets/rooms/gifts/cp/cp_06.gif','gif',10,'assets/rooms/gifts/cp/cp_06.gif',true),
  ('saki_cp_07','شمعة رومانسية','cp',3500,'💗','شمعة رومانسية','assets/rooms/gifts/cp/cp_07.gif',207,'assets/rooms/gifts/cp/cp_07.gif','gif',10,'assets/rooms/gifts/cp/cp_07.gif',true),
  ('saki_cp_08','عطر الحب','cp',4000,'💗','عطر الحب','assets/rooms/gifts/cp/cp_08.gif',208,'assets/rooms/gifts/cp/cp_08.gif','gif',10,'assets/rooms/gifts/cp/cp_08.gif',true),
  ('saki_cp_09','شوكولاتة فاخرة','cp',4500,'💗','شوكولاتة فاخرة','assets/rooms/gifts/cp/cp_09.gif',209,'assets/rooms/gifts/cp/cp_09.gif','gif',10,'assets/rooms/gifts/cp/cp_09.gif',true),
  ('saki_cp_10','كوبان دافئان','cp',5000,'💗','كوبان دافئان','assets/rooms/gifts/cp/cp_10.gif',210,'assets/rooms/gifts/cp/cp_10.gif','gif',10,'assets/rooms/gifts/cp/cp_10.gif',true),
  ('saki_cp_11','بالون قلب','cp',5500,'💗','بالون قلب','assets/rooms/gifts/cp/cp_11.gif',211,'assets/rooms/gifts/cp/cp_11.gif','gif',10,'assets/rooms/gifts/cp/cp_11.gif',true),
  ('saki_cp_12','حمام حب','cp',6000,'💗','حمام حب','assets/rooms/gifts/cp/cp_12.gif',212,'assets/rooms/gifts/cp/cp_12.gif','gif',10,'assets/rooms/gifts/cp/cp_12.gif',true),
  ('saki_cp_13','مظلة رومانسية','cp',6500,'💗','مظلة رومانسية','assets/rooms/gifts/cp/cp_13.gif',213,'assets/rooms/gifts/cp/cp_13.gif','gif',10,'assets/rooms/gifts/cp/cp_13.gif',true),
  ('saki_cp_14','مفتاح القلب','cp',7000,'💗','مفتاح القلب','assets/rooms/gifts/cp/cp_14.gif',214,'assets/rooms/gifts/cp/cp_14.gif','gif',10,'assets/rooms/gifts/cp/cp_14.gif',true),
  ('saki_cp_15','قفل الحب','cp',7500,'💗','قفل الحب','assets/rooms/gifts/cp/cp_15.gif',215,'assets/rooms/gifts/cp/cp_15.gif','gif',10,'assets/rooms/gifts/cp/cp_15.gif',true),
  ('saki_cp_16','جناحان من نور','cp',8000,'💗','جناحان من نور','assets/rooms/gifts/cp/cp_16.gif',216,'assets/rooms/gifts/cp/cp_16.gif','gif',10,'assets/rooms/gifts/cp/cp_16.gif',true),
  ('saki_cp_17','نجمان عاشقان','cp',8500,'💗','نجمان عاشقان','assets/rooms/gifts/cp/cp_17.gif',217,'assets/rooms/gifts/cp/cp_17.gif','gif',10,'assets/rooms/gifts/cp/cp_17.gif',true),
  ('saki_cp_18','قمر العاشقين','cp',9000,'💗','قمر العاشقين','assets/rooms/gifts/cp/cp_18.gif',218,'assets/rooms/gifts/cp/cp_18.gif','gif',10,'assets/rooms/gifts/cp/cp_18.gif',true),
  ('saki_cp_19','غروب رومانسي','cp',9500,'💗','غروب رومانسي','assets/rooms/gifts/cp/cp_19.gif',219,'assets/rooms/gifts/cp/cp_19.gif','gif',10,'assets/rooms/gifts/cp/cp_19.gif',true),
  ('saki_cp_20','موسيقى حب','cp',10000,'💗','موسيقى حب','assets/rooms/gifts/cp/cp_20.gif',220,'assets/rooms/gifts/cp/cp_20.gif','gif',10,'assets/rooms/gifts/cp/cp_20.gif',true),
  ('saki_cp_21','رقصة ثنائية','cp',10500,'💗','رقصة ثنائية','assets/rooms/gifts/cp/cp_21.gif',221,'assets/rooms/gifts/cp/cp_21.gif','gif',10,'assets/rooms/gifts/cp/cp_21.gif',true),
  ('saki_cp_22','قصر الحب','cp',11000,'💗','قصر الحب','assets/rooms/gifts/cp/cp_22.gif',222,'assets/rooms/gifts/cp/cp_22.gif','gif',10,'assets/rooms/gifts/cp/cp_22.gif',true),
  ('saki_cp_23','جزيرة رومانسية','cp',11500,'💗','جزيرة رومانسية','assets/rooms/gifts/cp/cp_23.gif',223,'assets/rooms/gifts/cp/cp_23.gif','gif',10,'assets/rooms/gifts/cp/cp_23.gif',true),
  ('saki_cp_24','مركب العاشقين','cp',12000,'💗','مركب العاشقين','assets/rooms/gifts/cp/cp_24.gif',224,'assets/rooms/gifts/cp/cp_24.gif','gif',10,'assets/rooms/gifts/cp/cp_24.gif',true),
  ('saki_cp_25','سيارة زفاف','cp',12500,'💗','سيارة زفاف','assets/rooms/gifts/cp/cp_25.gif',225,'assets/rooms/gifts/cp/cp_25.gif','gif',10,'assets/rooms/gifts/cp/cp_25.gif',true),
  ('saki_cp_26','كعكة زفاف','cp',13000,'💗','كعكة زفاف','assets/rooms/gifts/cp/cp_26.gif',226,'assets/rooms/gifts/cp/cp_26.gif','gif',10,'assets/rooms/gifts/cp/cp_26.gif',true),
  ('saki_cp_27','باقة فاخرة','cp',13500,'💗','باقة فاخرة','assets/rooms/gifts/cp/cp_27.gif',227,'assets/rooms/gifts/cp/cp_27.gif','gif',10,'assets/rooms/gifts/cp/cp_27.gif',true),
  ('saki_cp_28','قلادة قلب','cp',14000,'💗','قلادة قلب','assets/rooms/gifts/cp/cp_28.gif',228,'assets/rooms/gifts/cp/cp_28.gif','gif',10,'assets/rooms/gifts/cp/cp_28.gif',true),
  ('saki_cp_29','رسالة سرية','cp',14500,'💗','رسالة سرية','assets/rooms/gifts/cp/cp_29.gif',229,'assets/rooms/gifts/cp/cp_29.gif','gif',10,'assets/rooms/gifts/cp/cp_29.gif',true),
  ('saki_cp_30','حب أبدي','cp',15000,'💗','حب أبدي','assets/rooms/gifts/cp/cp_30.gif',230,'assets/rooms/gifts/cp/cp_30.gif','gif',10,'assets/rooms/gifts/cp/cp_30.gif',true),
  ('saki_country_sa','السعودية • برج المملكة','countries',300,'🇸🇦','السعودية • برج المملكة','assets/rooms/gifts/countries/sa.png',301,'assets/rooms/gifts/countries/sa.png','image',10,'assets/rooms/gifts/countries/sa.png',true),
  ('saki_country_ae','الإمارات • برج خليفة','countries',600,'🇦🇪','الإمارات • برج خليفة','assets/rooms/gifts/countries/ae.png',302,'assets/rooms/gifts/countries/ae.png','image',10,'assets/rooms/gifts/countries/ae.png',true),
  ('saki_country_qa','قطر • متحف قطر','countries',900,'🇶🇦','قطر • متحف قطر','assets/rooms/gifts/countries/qa.png',303,'assets/rooms/gifts/countries/qa.png','image',10,'assets/rooms/gifts/countries/qa.png',true),
  ('saki_country_kw','الكويت • أبراج الكويت','countries',1200,'🇰🇼','الكويت • أبراج الكويت','assets/rooms/gifts/countries/kw.png',304,'assets/rooms/gifts/countries/kw.png','image',10,'assets/rooms/gifts/countries/kw.png',true),
  ('saki_country_bh','البحرين • قلعة البحرين','countries',1500,'🇧🇭','البحرين • قلعة البحرين','assets/rooms/gifts/countries/bh.png',305,'assets/rooms/gifts/countries/bh.png','image',10,'assets/rooms/gifts/countries/bh.png',true),
  ('saki_country_om','عُمان • قلعة نزوى','countries',1800,'🇴🇲','عُمان • قلعة نزوى','assets/rooms/gifts/countries/om.png',306,'assets/rooms/gifts/countries/om.png','image',10,'assets/rooms/gifts/countries/om.png',true),
  ('saki_country_ye','اليمن • صنعاء القديمة','countries',2100,'🇾🇪','اليمن • صنعاء القديمة','assets/rooms/gifts/countries/ye.png',307,'assets/rooms/gifts/countries/ye.png','image',10,'assets/rooms/gifts/countries/ye.png',true),
  ('saki_country_eg','مصر • أهرامات الجيزة','countries',2400,'🇪🇬','مصر • أهرامات الجيزة','assets/rooms/gifts/countries/eg.png',308,'assets/rooms/gifts/countries/eg.png','image',10,'assets/rooms/gifts/countries/eg.png',true),
  ('saki_country_sd','السودان • أهرامات مروي','countries',2700,'🇸🇩','السودان • أهرامات مروي','assets/rooms/gifts/countries/sd.png',309,'assets/rooms/gifts/countries/sd.png','image',10,'assets/rooms/gifts/countries/sd.png',true),
  ('saki_country_ly','ليبيا • قوس ماركوس أوريليوس','countries',3000,'🇱🇾','ليبيا • قوس ماركوس أوريليوس','assets/rooms/gifts/countries/ly.png',310,'assets/rooms/gifts/countries/ly.png','image',10,'assets/rooms/gifts/countries/ly.png',true),
  ('saki_country_tn','تونس • مدرج الجم','countries',3300,'🇹🇳','تونس • مدرج الجم','assets/rooms/gifts/countries/tn.png',311,'assets/rooms/gifts/countries/tn.png','image',10,'assets/rooms/gifts/countries/tn.png',true),
  ('saki_country_dz','الجزائر • مقام الشهيد','countries',3600,'🇩🇿','الجزائر • مقام الشهيد','assets/rooms/gifts/countries/dz.png',312,'assets/rooms/gifts/countries/dz.png','image',10,'assets/rooms/gifts/countries/dz.png',true),
  ('saki_country_ma','المغرب • ساحة جامع الفنا','countries',3900,'🇲🇦','المغرب • ساحة جامع الفنا','assets/rooms/gifts/countries/ma.png',313,'assets/rooms/gifts/countries/ma.png','image',10,'assets/rooms/gifts/countries/ma.png',true),
  ('saki_country_mr','موريتانيا • مدينة شنقيط','countries',4200,'🇲🇷','موريتانيا • مدينة شنقيط','assets/rooms/gifts/countries/mr.png',314,'assets/rooms/gifts/countries/mr.png','image',10,'assets/rooms/gifts/countries/mr.png',true),
  ('saki_country_so','الصومال • شاطئ ليدو','countries',4500,'🇸🇴','الصومال • شاطئ ليدو','assets/rooms/gifts/countries/so.png',315,'assets/rooms/gifts/countries/so.png','image',10,'assets/rooms/gifts/countries/so.png',true),
  ('saki_country_dj','جيبوتي • بحيرة عسل','countries',4800,'🇩🇯','جيبوتي • بحيرة عسل','assets/rooms/gifts/countries/dj.png',316,'assets/rooms/gifts/countries/dj.png','image',10,'assets/rooms/gifts/countries/dj.png',true),
  ('saki_country_km','جزر القمر • بركان كارتالا','countries',5100,'🇰🇲','جزر القمر • بركان كارتالا','assets/rooms/gifts/countries/km.png',317,'assets/rooms/gifts/countries/km.png','image',10,'assets/rooms/gifts/countries/km.png',true),
  ('saki_country_lb','لبنان • أرز لبنان','countries',5400,'🇱🇧','لبنان • أرز لبنان','assets/rooms/gifts/countries/lb.png',318,'assets/rooms/gifts/countries/lb.png','image',10,'assets/rooms/gifts/countries/lb.png',true),
  ('saki_country_sy','سوريا • قلعة حلب','countries',5700,'🇸🇾','سوريا • قلعة حلب','assets/rooms/gifts/countries/sy.png',319,'assets/rooms/gifts/countries/sy.png','image',10,'assets/rooms/gifts/countries/sy.png',true),
  ('saki_country_jo','الأردن • البتراء','countries',6000,'🇯🇴','الأردن • البتراء','assets/rooms/gifts/countries/jo.png',320,'assets/rooms/gifts/countries/jo.png','image',10,'assets/rooms/gifts/countries/jo.png',true),
  ('saki_country_iq','العراق • زقورة أور','countries',6300,'🇮🇶','العراق • زقورة أور','assets/rooms/gifts/countries/iq.png',321,'assets/rooms/gifts/countries/iq.png','image',10,'assets/rooms/gifts/countries/iq.png',true),
  ('saki_country_ps','فلسطين • قبة الصخرة','countries',6600,'🇵🇸','فلسطين • قبة الصخرة','assets/rooms/gifts/countries/ps.png',322,'assets/rooms/gifts/countries/ps.png','image',10,'assets/rooms/gifts/countries/ps.png',true)
on conflict (category, name) do update set
  price=excluded.price, icon=excluded.icon, media_url=excluded.media_url,
  media_type=excluded.media_type, duration_seconds=10,
  thumbnail_url=excluded.thumbnail_url, is_active=true, sort_order=excluded.sort_order;
