create table if not exists public.saki_wheel_rounds (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  round_no bigint not null,
  status text not null default 'betting' check (status in ('betting','result','settled')),
  betting_ends_at timestamptz not null,
  result_ends_at timestamptz not null,
  winning_food text,
  created_at timestamptz not null default now(),
  unique(room_id, round_no)
);
create table if not exists public.saki_wheel_bets (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.saki_wheel_rounds(id) on delete cascade,
  room_id uuid not null references public.rooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  food_key text not null,
  amount bigint not null check (amount > 0),
  created_at timestamptz not null default now()
);
create index if not exists saki_wheel_round_room_idx on public.saki_wheel_rounds(room_id, created_at desc);
create index if not exists saki_wheel_bet_round_user_idx on public.saki_wheel_bets(round_id, user_id, food_key);
alter table public.saki_wheel_rounds enable row level security;
alter table public.saki_wheel_bets enable row level security;
drop policy if exists wheel_round_read on public.saki_wheel_rounds;
create policy wheel_round_read on public.saki_wheel_rounds for select to authenticated using (true);
drop policy if exists wheel_bet_read on public.saki_wheel_bets;
create policy wheel_bet_read on public.saki_wheel_bets for select to authenticated using (user_id = auth.uid() or public.is_saki_super_admin());

create or replace function public.saki_wheel_current_round(p_room_id uuid)
returns public.saki_wheel_rounds language plpgsql security definer set search_path=public as $$
declare r public.saki_wheel_rounds; n bigint;
begin
 select * into r from saki_wheel_rounds where room_id=p_room_id and status <> 'settled' order by id desc limit 1;
 if r.id is not null then return r; end if;
 select coalesce(max(round_no),0)+1 into n from saki_wheel_rounds where room_id=p_room_id;
 insert into saki_wheel_rounds(room_id,round_no,status,betting_ends_at,result_ends_at)
 values(p_room_id,n,'betting',now()+interval '15 seconds',now()+interval '25 seconds') returning * into r;
 return r;
end; $$;

create or replace function public.saki_wheel_place_bet(p_room_id uuid,p_food_key text,p_amount bigint)
returns table(round_id bigint,food_key text,amount bigint,gold_coins bigint)
language plpgsql security definer set search_path=public as $$
declare r public.saki_wheel_rounds; balance bigint;
begin
 if p_amount not in (10,100,1000,10000,100000) then raise exception 'invalid_wheel_amount'; end if;
 if p_food_key not in ('tomato','burger','cake','pizza','shrimp','ice_cream','orange','corn','carrot') then raise exception 'invalid_wheel_food'; end if;
 select * into r from public.saki_wheel_current_round(p_room_id);
 if r.status <> 'betting' or now() >= r.betting_ends_at then raise exception 'wheel_betting_closed'; end if;
 update saki_account_modules set gold_coins=gold_coins-p_amount,updated_at=now() where user_id=auth.uid() and gold_coins>=p_amount;
 if not found then raise exception 'insufficient_gold'; end if;
 insert into saki_wheel_bets(round_id,room_id,user_id,food_key,amount) values(r.id,p_room_id,auth.uid(),p_food_key,p_amount);
 select m.gold_coins into balance from saki_account_modules m where m.user_id=auth.uid();
 return query select r.id,p_food_key,p_amount,balance;
end; $$;

create or replace function public.saki_wheel_resolve(p_round_id bigint)
returns public.saki_wheel_rounds language plpgsql security definer set search_path=public as $$
declare r public.saki_wheel_rounds; pick double precision; winner text; payout record;
begin
 select * into r from saki_wheel_rounds where id=p_round_id for update;
 if r.status='settled' then return r; end if;
 if now() < r.betting_ends_at then raise exception 'wheel_betting_not_finished'; end if;
 if r.status='betting' then
   pick := random();
   winner := case when pick < .03 then 'burger' when pick < .08 then 'tomato' when pick < .18 then 'cake' when pick < .33 then 'pizza' when pick < .43 then 'shrimp' when pick < .55 then 'ice_cream' when pick < .70 then 'orange' when pick < .85 then 'corn' else 'carrot' end;
   update saki_wheel_rounds set status='result',winning_food=winner where id=r.id returning * into r;
   for payout in select user_id,sum(amount)::bigint total from saki_wheel_bets where round_id=r.id and food_key=winner group by user_id loop
     update saki_account_modules set gold_coins=gold_coins+(payout.total * case winner when 'burger' then 45 when 'tomato' then 100 when 'cake' then 25 when 'pizza' then 15 when 'shrimp' then 10 when 'ice_cream' then 7 when 'orange' then 5 when 'corn' then 5 else 3 end),updated_at=now() where user_id=payout.user_id;
   end loop;
 end if;
 if now() >= r.result_ends_at then update saki_wheel_rounds set status='settled' where id=r.id returning * into r; end if;
 return r;
end; $$;
revoke all on function public.saki_wheel_current_round(uuid),public.saki_wheel_place_bet(uuid,text,bigint),public.saki_wheel_resolve(bigint) from public;
grant execute on function public.saki_wheel_current_round(uuid),public.saki_wheel_place_bet(uuid,text,bigint),public.saki_wheel_resolve(bigint) to authenticated;
